### ISSUE TITLE
Type Inference for structural types

### ISSUE THREAD

**Issue by DatenMetzgerX** [DatenMetzgerX/ESChecker#23]
The type inference algorithm needs to support structural types, also known as record types. The order in which the record type properties occur is not important.

A record type defines the shape of an object literal, but is not used to describe classes, even if both semantics are very similar. The important difference is that classes use nominal typing (subtyping is not given by having the same structure). 

A record type is defined as 

```
record = propList
probList = prop | prop propList
prop = name : t
```

where a property has a label (it's name) and a type.

**Unification:**
The unification of the record types is a new record type that contains the properties of both types. 
The unification (or subtyping) for type S and T fails if S does not contain at least the properties of T or where the property types cannot be unified. The order of the property names doesn't matter. To simplify the ordering it's suggested to keep an ordered Set with the property names in a record. 

**Involved expressions:**

- Object Literal
- Assignment Expression where the left hand side is a PropertyExpression

**Tasks**
- [x] Extending Symbol extraction algorithm for object literals
- [x] Definition of record type. The record type needs to override equals as the equality of a record type is not given by just comparing the parameter types. 
- [x] Adding refinement rule for object literals and adjusting the assignment expression refinement rule.
- [x] The unification rule for *same* types needs to be extracted or adjusted so that it does not apply for Records. Records unification is not only based on the type parameter but also with the associated names. 

 Implementing the unification of record types

Record types can only be unified with other record types or with null, which leads to Maybe<Record>
